#!/usr/bin/env node
import { program } from 'commander';
import path from 'path';
import fs from 'fs-extra';
import type { VideoConfig, BrandColors } from '../types/index.js';

const PROJECTS_ROOT = path.resolve(process.cwd(), 'projects');

program
  .requiredOption('--name <name>', 'Project name (kebab-case, e.g. nike-summer-ad)')
  .requiredOption(
    '--format <format>',
    'Video format: youtube-short | tiktok | ad-16x9 | ad-1x1 | web-hero',
  )
  .parse();

const opts = program.opts<{ name: string; format: string }>();
const projectName = opts.name.toLowerCase().replace(/\s+/g, '-');
const format = opts.format;

const VALID_FORMATS = ['youtube-short', 'tiktok', 'ad-16x9', 'ad-1x1', 'web-hero'];
if (!VALID_FORMATS.includes(format)) {
  console.error(`❌ Invalid format: "${format}". Valid: ${VALID_FORMATS.join(' | ')}`);
  process.exit(1);
}

const projectDir = path.join(PROJECTS_ROOT, projectName);

async function scaffold(): Promise<void> {
  if (await fs.pathExists(projectDir)) {
    console.error(`❌ Project "${projectName}" already exists at ${projectDir}`);
    process.exit(1);
  }

  // Create all directories
  const dirs = [
    'assets/brand',
    'assets/reference',
    'assets/storyboard',
    'assets/audio/sfx',
    'cache',
    'output/audio',
    'output/clips',
    'output/frames',
    'output/final',
  ];

  for (const dir of dirs) {
    await fs.mkdirp(path.join(projectDir, dir));
  }

  // Write config.json with format-appropriate defaults
  const defaultCaptions = format === 'youtube-short' || format === 'tiktok';
  const config: VideoConfig = {
    format: format as VideoConfig['format'],
    title: projectName,
    script: '',
    voiceId: 'pNInz6obpgDQGcFmaJgB', // ElevenLabs Adam voice — change this
    clips: [
      {
        prompt: 'Describe your first scene here',
        duration: 5,
      },
    ],
    transition: 'crossfade',
    captions: defaultCaptions,
    captionStyle: 'word-by-word',
    captionPosition: 'bottom',
    hookText: '',
    music: false,
    musicVolume: 0.15,
  };
  await fs.writeJson(path.join(projectDir, 'config.json'), config, { spaces: 2 });

  // Write brand.json template
  const brand: BrandColors = {
    primary: '#FFFFFF',
    secondary: '#000000',
    accent: '#FF0000',
  };
  await fs.writeJson(path.join(projectDir, 'assets/brand/brand.json'), brand, { spaces: 2 });

  // Write storyboard README
  await fs.writeFile(
    path.join(projectDir, 'assets/storyboard/README.md'),
    `# Storyboard Images

## How This Works

Storyboard images are the key to visual consistency across your video. They bridge
Gemini's image generation with Kling's video generation.

## Naming Convention

- \`scene-1.png\` — First frame fed into Kling to start the clip
- \`scene-1-lastframe.png\` — AUTO-GENERATED by pipeline from Kling output. Open in Gemini to generate scene 2.
- \`scene-2.png\` — Generated by Gemini looking at scene-1-lastframe.png
- Repeat for all scenes.

## Workflow

1. Add \`../reference/style.jpg\` (sets the visual vibe)
2. Switch to Gemini in Antigravity: "Generate scene 1 image in the style of [describe reference]"
3. Save Gemini's output here as \`scene-1.png\`
4. Run pipeline — it generates the Kling clip and saves \`scene-1-lastframe.png\`
5. Show Gemini the lastframe: "Continue this scene naturally, generate scene 2"
6. Repeat

## Image Requirements

- Format: PNG (preferred) or JPG
- Resolution: Minimum 768x768, ideally 1080x1920 for 9:16 or 1920x1080 for 16:9
- Content: Static, high-quality image that represents the start of the scene

## Auto-Discovery

The pipeline automatically finds all \`scene-N.png\` files in this folder in order.
You do not need to update config.json when adding new scenes — just drop the PNG here.
`,
  );

  // Write audio README
  await fs.writeFile(
    path.join(projectDir, 'assets/audio/README.md'),
    `# Audio Assets

## Background Music (optional)

Place a royalty-free music track here as \`music.mp3\`.

**Recommended sources:**
- Epidemic Sound (epidemicsound.com) — paid, broadcast-quality
- Pixabay Music (pixabay.com/music) — free
- Freesound (freesound.org) — free with attribution
- Artlist (artlist.io) — paid, unlimited license

**Requirements:**
- Format: MP3 (preferred) or WAV
- Sample rate: 44100 Hz
- Bitrate: 192 kbps or higher
- Duration: Longer than the final video (pipeline loops/trims automatically)

## Sound Effects (optional)

Place .mp3 or .wav files inside the \`sfx/\` folder.
Name them descriptively, e.g. \`swoosh.mp3\`, \`ding.wav\`.

## Voiceover

Voiceover is AUTO-GENERATED by ElevenLabs from the script in config.json.
The output is saved to: \`../../output/audio/voiceover.mp3\`
`,
  );

  // Print next steps
  console.log(`
✅ Project "${projectName}" created!

Before running the pipeline, follow these steps in order:

STEP 1 — Add your style reference (most important for visual consistency):
  → Drop a reference image into: projects/${projectName}/assets/reference/style.jpg
  → This sets the visual mood. Use a film still, photo, or any image with the right vibe.

STEP 2 — Switch to Gemini inside Antigravity and ask it:
  → "Generate a storyboard image for scene 1 in the style of [describe your reference image]"
  → Save Gemini's output to: projects/${projectName}/assets/storyboard/scene-1.png

STEP 3 — Add your brand assets (for client work):
  → Logo: projects/${projectName}/assets/brand/logo.png (transparent background)
  → Colors: edit projects/${projectName}/assets/brand/brand.json

STEP 4 — Add background music (optional):
  → projects/${projectName}/assets/audio/music.mp3

STEP 5 — Edit your video config:
  → projects/${projectName}/config.json

STEP 6 — Run the pipeline:
  → npm run pipeline -- --project ${projectName}
`);
}

scaffold().catch((err: unknown) => {
  console.error('❌ Scaffolding failed:', err);
  process.exit(1);
});
